### ISSUE TITLE
An account is not created when registering on the site.

### ISSUE THREAD

**Issue by minter69** [UBrainDev/btc-faucet#2]
For some reason, an account is not created when registering on the site. No registration data is displayed in the database. When you register, you simply redirect to the next section of the site without authorization. Everything else seems to work, but it is the authorization itself that does not. I can easily walk through the rest of the site, but without authorization. Where the captcha is in the code, I changed it, but it's not about it. What's wrong?

**Comment by urbainn** [comment]
Are you sure that the `.sql` file has been correctly imported, and that the tables are not locked?

**Comment by minter69** [comment]
> Are you sure that the `.sql` file has been correctly imported, and that the tables are not locked?

If you create an account manually through the database, you can then log into the account. but before that it was necessary to remove the exclamation mark in line 114 in the login.php. But if you register through the site, then an account is not created. I tried several times to reinstall the database on different hosting, but the result is the same

**Comment by urbainn** [comment]
I see. I tried reinstalling the whole code on a local folder, and it worked perfectly. I honestly think that you misconfigured the template, could you try setting it up again? Otherwise, it shouldn't be possible to create an account in the database, as passwords are encrypted. The problem could be the PHP version, but I doubt it; try checking it, and if it is below version 7.1, try upgrading.
